spring:
  application:
    name: coupon-challenge

server:
  port: 8081


app:
  api:
    meli: https://api.mercadolibre.com
    id: 6108866500380003
    client-secret: bjAK91iRzT0ERGRi4nydLlB7Z6yPUVlX



